source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "7.0"

target "imoji-collection-view", :exclusive => true do
  pod 'Masonry'
  pod 'ImojiSDK'
  pod 'CocoaLumberjack'
  pod 'ImojiSDKUI', :path => '../..'
end
