source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target "imoji-keyboard" do
  pod 'ImojiSDKUI', :path => '../../'
end

target "keyboard" do
  pod 'ImojiSDKUI', :path => '../../'
end
