source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "7.0"

pod 'ImojiSDKUI/CollectionView', :git => "https://github.com/imojiengineering/imoji-ios-sdk-ui"
pod 'ImojiSDKUI/Editor', :git => "https://github.com/imojiengineering/imoji-ios-sdk-ui"
pod 'Masonry'
