source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

use_frameworks!

target "artmoji" do
    pod 'ImojiSDKUI/CollectionView'
    pod 'ImojiSDKUI/Editor'
end

target "artmoji-photos" do
    pod 'ImojiSDKUI/CollectionView'
    pod 'ImojiSDKUI/Editor'
end