source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target "artmoji" do
    pod 'PBJVision'
    pod 'ImojiSDKUI/CollectionView', :path => "../../"
    pod 'ImojiSDKUI/Editor', :path => "../../"
end

target "artmoji-photos" do
    pod 'ImojiSDKUI/CollectionView', :path => "../../"
    pod 'ImojiSDKUI/Editor', :path => "../../"
end